### ISSUE TITLE
Server Setting and Getting Fields returns ValueError

### ISSUE THREAD

**Issue by terrence-yu** [Saveyour-Team/SaveYourServer#2]
encrypt returns "Invalid Salt" in Server Tests:

```
    FileManager.setField("BeAutY", "usr", "Sleeping")
    self.assertTrue(Login.authenticateHashed("Sleeping", "Sleeping"))
```

**Comment by bpteich** [comment]
Thats because you set pwd to an unhashed password. Use the newPassword command instead

**Comment by bpteich** [comment]
Or are you trying to rename a user? That's not supported
